### ISSUE TITLE
panic: runtime error: assignment to entry in nil map

### ISSUE THREAD

**Issue by yuya-takeyama** [yuya-takeyama/dbyaml2md#6]
```
panic: runtime error: assignment to entry in nil map

goroutine 16 [running]:
runtime.panic(0x59d7e0, 0x6befb3)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*MdWriter).writeMarkdownFromTable(0xc208a95220, 0x2b95842cfb18, 0xc208a95218, 0xc2087285a0, 0x0, 0x0)
        /home/vagrant/src/github.com/yuya-takeyama/dbyaml2md/md_writer.go:51 +0x10d
main.generateMarkdownFiles(0xc2088d9b50, 0x0, 0x0)
        /home/vagrant/src/github.com/yuya-takeyama/dbyaml2md/main.go:96 +0x37c
main.func·001(0xc20804c160)
        /home/vagrant/src/github.com/yuya-takeyama/dbyaml2md/main.go:75 +0x314
github.com/codegangsta/cli.(*App).Run(0xc20804a0c0, 0xc20800e000, 0x2, 0x2, 0x0, 0x0)
        /home/vagrant/src/github.com/codegangsta/cli/app.go:130 +0x98a
main.main()
        /home/vagrant/src/github.com/yuya-takeyama/dbyaml2md/main.go:78 +0x222

goroutine 19 [finalizer wait]:
runtime.park(0x4146e0, 0x6c2b08, 0x6c1649)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x6c2b08, 0x6c1649)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445
```

**Comment by yuya-takeyama** [comment]
This seems to reproduce when `front_matter` is not set in config.
